### ISSUE TITLE
Typos in the Technique part 

### ISSUE THREAD

**Issue by Yuuoniy** [mitre-attack/attack-website#1]
I don't if anyone maintain this repo, It seems there is a typo in T1155.
As in the website, the last sentence introducing AppleScript is：

> Scripts can be run from the command lie via osascript /path/to/script or osascript -e "script here".

I guess it should be **command line**  rather than **command lie**，command lie doesn't make sense.
Please check for it.

**Comment by Yuuoniy** [comment]
In T1150( Plist Modification）
The second sentence:
`These files are UT-8 encoded and formatted like XML documents via a series of keys surrounded by < >.`
May be it should be **UTF-8** rather than **UT-8**

**Comment by Yuuoniy** [comment]
Hi, @jburns12
 I'm sorry to bother you, would you please check for the problems I mentioned above？

**Comment by Yuuoniy** [comment]
In T1310 (Acquire or compromise 3rd party signing certificates)

> Users may trust **a signed** piece of code more than **an signed** piece of code even if they don't know who issued the certificate or who the author is. 

the second **signed** may be should be **unsigned** ，otherwise, it has no sense.

**Comment by jburns12** [comment]
Hi @Yuuoniy -

Thanks so much for submitting these! We'll get these fixes implemented in an upcoming update to the ATT&CK website.

For future issues, you can send an email to attack@mitre.org with the title **Website Content Error**. We just posted some instructions to our [README](https://github.com/mitre-attack/attack-website) on what to send us in the email, and these instructions will also be posted on our [contribute](https://attack.mitre.org/resources/contribute) page in the near future.

Thanks again for bringing these to our attention!
