### ISSUE TITLE
In the card on techniques pages, the entries for sub-techniques should be hyperlinks

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#103]
As a user of the ATT&CK Website, I want it to be easy to navigate between techniques and their sub-techniques.

On technique pages, the data-card on the right-side lists sub-techniques by ID. However, the entries of this list are not hyperlinks. We should make them into hyperlinks so that it's easy to navigate the site.

Additionally, on a sub-technique page, the parent technique ID should be added to the data-card with a hyperlink to the technique. E.g `sub-technique of: T1001`

**Comment by IanDavila** [comment]
Staged on the `subtechniques-2.1` branch
