### ISSUE TITLE
Deprecated techniques should not show any content

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#116]
As a maintainer of ATT&CK, I want to make sure people don't continue to use deprecated techniques, but I want users to be able to tell that a technique is deprecated and the justification for the deprecation.

The first paragraph of a deprecated technique's description in the STIX should be the deprecation justification and/or a list of replacing objects. Further paragraphs of the description (the previous content of the object) will be omitted from the page. They’ll persist in the STIX but not on the site.

The "DEPRECATED" marking will be added automatically and needn't be added to the first paragraph of the deprecated object's description.

**Comment by isaisabel** [comment]
Deprecated techniques will need to be omitted from all lists (relationships, technique lists, tactics, etc) if they aren't already.

**Comment by isaisabel** [comment]
I'll work on this the part outlined in this comment @IanDavila and we can merge into feature/subtechniques separately.

Deprecated objects should have the following tag added to their head to stop search engines from showing the page:

```
<meta name="robots" content="noindex, nofollow">
```

Additionally, our search feature should avoid display results which have that tag.

**Comment by isaisabel** [comment]
Implemented in `feature/#116-deprecated-nosearch`. @IanDavila is there any risk of you changing the `parsed.deprecated` field for software, migitation, group, or technique pages? That's the only possible compatibility snafu as far as I can think.

**Comment by IanDavila** [comment]
> Implemented in `feature/#116-deprecated-nosearch`. @IanDavila is there any risk of you changing the `parsed.deprecated` field for software, migitation, group, or technique pages? That's the only possible compatibility snafu as far as I can think.

@isaisabel I will not change the `parsed.deprecated` field for any of the pages.

**Comment by isaisabel** [comment]
Thanks, I've merged the deprecated-nosearch branch into subtechniques independently of your branch.
