### ISSUE TITLE
Add sub-technique count to tactic/techniques list

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#119]
As a user of the ATT&CK Website, I want to be able to see a count of sub-techniques under the given domain. 

We should augment the existing "techniques count in domain" with a count of the sub-techniques in the domain.

<img width="1100" alt="Screen Shot 2020-03-27 at 7 47 07 AM" src="https://user-images.githubusercontent.com/28868888/77753113-397c1c00-6fff-11ea-98ea-9e48841336f5.png">

**Comment by IanDavila** [comment]
Staged in `subtechniques-2.1`
