### ISSUE TITLE
broken link in changelog

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#122]
The link to the MITRE/CTI repo for the 7.0-beta release is broken: https://github.com/mitre/cti/releases/tag/ATT%26CK-v7.0-beta

**Comment by IanDavila** [comment]
Link pointed to commit https://github.com/mitre/cti/tree/4d3f22d81af2424f3885b4390793ee8eb256d10d.

Staged: `subtechniques-2.1`
