### ISSUE TITLE
sub-techniques and sibling-sub-techniques panels need to be excluded from search

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#123]
The content of these panels needs to be excluded from the search parser:
![image](https://user-images.githubusercontent.com/28868888/78056648-7b84c500-7353-11ea-8f1e-d2c46757ad36.png)

![image](https://user-images.githubusercontent.com/28868888/78056666-817aa600-7353-11ea-91e0-4acea721b88a.png)

**Comment by IanDavila** [comment]
Staged: `subtechniques-2.1`
