### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#181]
As a user of the ATT&CK website, I want to make sure that the dependencies are up-to-date to ensure that the build process is fast and contains no bugs.

1. Check [the dependabot pull requests](https://github.com/mitre-attack/attack-website/pulls/app%2Fdependabot) to ensure that they don't break anything, and merge them if possible.
2. Upgrade jquery to version 3.5.0 or later if possible
3. Upgrade Jinja2 to version 2.10.1 or later if possible

**Comment by IanDavila** [comment]
Staged in modularization-3.0 branch
