### ISSUE TITLE
Training Pages

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#22]
As a user of the ATT&CK website, I want to be able to find training information for how to use ATT&CK.

The URLs will follow this format:
```
/resources/training (landing page)
                   /cti (topic intro)
                       /exercise1
                       /exercise2
                       /exercise3
                       /exercise4
                   /mappings (topic intro)
                       /exercise1
                       /exercise2
                       /exercise3
                       /exercise4
                   (etc)
```

Redirects will be created from `/training` to `/resources/training` and from `/training/topic` to `/resources/training/topic` for each topic. 

These pages should make use of the sidebar macro for navigation. Each exercise should have a "previous" and "next" exercise button under the exercise content.

**Comment by klq223** [comment]
Shared format for CTI training modules for addition to website - details on internal site.

**Comment by adampennin** [comment]
Shared proposed site updates with @isaisabel and @IanDavila via an emailed patch.
