### ISSUE TITLE
Mitre Att&ck Data Sources and Techniques Visual Not Available

### ISSUE THREAD

**Issue by iukenbo** [mitre-attack/attack-website#224]
https://attack.mitre.org/theme/images/TechData.png.html

Shows 404 error.

**Comment by isaisabel** [comment]
Hi @iukenbo,
Removing the `.html` from the end of the URL should lead to the correct graphic:
https://attack.mitre.org/theme/images/TechData.png

I believe that we have a blog post that links to the `.html` versions of those visualizations, but I'm not sure if we're planning on updating it with the new URLs.

**Comment by iukenbo** [comment]
Working now.

Thank you!
