### ISSUE TITLE
add Linux as OS for T1037

### ISSUE THREAD

**Issue by attackjunkee** [mitre-attack/attack-website#225]
/etc/inittab allows for startup scripts during boot.

This issue refers to the MITRE website page: https://attack.mitre.org/techniques/T1037/

My reference for inittab is: https://www.thegeekdiary.com/understanding-the-etc-inittab-file-in-linux/

Great Work, and thankyou for your consideration!

**Comment by isaisabel** [comment]
Hi @attackjunkee,

Thank you for reaching out! Please see our [contribute page](https://attack.mitre.org/resources/contribute/) for more information about contributing to ATT&CK. Generally, contributions to the ATT&CK knowledge base should be submitted via email to attack@mitre.org. This issue tracker is mainly for the format and features of the website, not so much the content.

Thanks!
