### ISSUE TITLE
Generate layers for mitigations

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#234]
As a user of the ATT&CK website, I want to be able to access ATT&CK Navigator layers representing the "Techniques Addressed by Mitigation" table, just like the ones already available for the "Techniques Used" tables on the group and software pages:

![Screen Shot 2020-08-26 at 1 57 48 PM](https://user-images.githubusercontent.com/28868888/91339203-26cf6400-e7a4-11ea-87f2-6089a76b1c0c.png)

**Comment by IanDavila** [comment]
Will update navigator support to 4.1->4.2
