### ISSUE TITLE
Add IDs to procedure examples table

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#236]
As a user of the ATT&CK website, I want to be able to see ATT&CK IDs when I'm browsing the procedure examples tables:
![image](https://user-images.githubusercontent.com/28868888/91340089-69457080-e7a5-11ea-98c5-db98bd354e10.png)

Note: the ID should not be added just as a column, because some users may interpret this as the ID of the _procedure_ and not of the attached object. One possible solution would be to have it as a tooltip on the object name, although it would probably be better to have it visible without the user needing to mouse-over.

See also #235.

**Comment by IanDavila** [comment]
I thinking adding the ID column is not a bad idea, it looks like that all around the website, I doubt users will think that it is the ID of the procedure since it will have a Group of Software ID structure.

**Comment by IanDavila** [comment]
![Screen Shot 2021-04-20 at 10 55 33 AM](https://user-images.githubusercontent.com/12372037/115417874-fe7af680-a1c6-11eb-9530-1c58dec01289.png)

Similar to the Techniques Used table

**Comment by IanDavila** [comment]
We should also add IDs to the software and groups pages (https://attack.mitre.org/software/, https://attack.mitre.org/groups/) to have IDs on all of our tables.

**Comment by isaisabel** [comment]
Yeah seeing this in practice it looks fine to have IDs in their own column.
