### ISSUE TITLE
Add ATT&CK for ICS domain

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#272]
As a user of ATT&CK for ICS, I want to be able to see the ICS dataset on the main ATT&CK website.

Currently the ATT&CK for ICS domain is held on a separate site (http://collaborate.mitre.org/attackics/). Now that STIX data for ICS has been released, we should consider moving it over to the main website for consistency of representation.

**Comment by jondricek** [comment]
This has been implemented with the 3.6.0 website release for ATT&CK v11
