### ISSUE TITLE
Add Export Software Functionality

### ISSUE THREAD

**Issue by AOrps** [mitre-attack/attack-website#301]
It would a really cool enhancement to be able to export the list of software on the attack-website into a CSV or something else. Unsure if this is a realistic feature, given the current workload. Just thought it might be something useful.

**Comment by isaisabel** [comment]
HI @AOrps,
We've actually already recently added this feature. You can find excel files representing ATT&CK on the newly revised [Working with ATT&CK](https://attack.mitre.org/resources/working-with-attack/) page!

**Comment by isaisabel** [comment]
I should note that due to a bug (due to be resolved shortly by #297) groups excel file is not listed. The file exists (you can find it if you follow the URL pattern for the other spreadsheets) there's just no link to it in the list.

**Comment by AOrps** [comment]
Thanks! Apologies for the duplicate.
