### ISSUE TITLE
Provide an updated PDF version of the Matrix

### ISSUE THREAD

**Issue by aidenmitchell** [mitre-attack/attack-website#324]
Currently, the [last updated version](https://attack.mitre.org/docs/attack_matrix_poster_2020_october.pdf) of the PDF version of the ATT&CK matrix was from October 2020, whereas the matrix was last updated in April 2021.
Additionally, the PDF version should be made more available on the site, as it is difficult to find the latest version.

**Comment by isaisabel** [comment]
Hi @aidenmitchell,

We actually do have a more recently updated matrix poster on the website (updated June 2021): https://attack.mitre.org/docs/attack_matrix_poster_2021_june.pdf

You can find this on the general information page: https://attack.mitre.org/resources/

We do preserve older versions of the poster on the site in the `/docs/` folder, so the hyperlink to the most up-to-date matrix will change for each update.
