### ISSUE TITLE
Dockerfile exits with nonzero status code due to test warnings

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#326]
As a user of the ATT&CK Website, I want to be able to build the site with the dockerfile even if built-in tests produce non-breaking warnings.

Currently the attack-website build fails in the dockerfile because the website test warnings for internal links cause a non-zero exit code. Adding the `--no-test-existstatus` flag when the build script is executed in the dockerfile may fix this issue since it will suppress those status-codes when the tests produce a warning.

**Comment by dickens88** [comment]
@isaisabel 
I try to build this project follow this `readme.md` without Docker. but it also failed to pass the test. it there any workaround way to solve the problem?

![image](https://user-images.githubusercontent.com/8390209/129303284-8e89acc4-c661-4071-bf07-ee4bbcc25f05.png)

**Comment by isaisabel** [comment]
Hi @dickens88,

Those are really more warnings than failures, you can still use the site with them present. The broken links test is reporting that some links exist to `/resources/` pages which were not built. If you run the build script with the `--extras` flag it should build the `/resources/` pages and thereby avoid that issue.

**Comment by dickens88** [comment]
ooh, yes, you are right, thank you so much for the reply.
