### ISSUE TITLE
Got error when trying to sync data from ATT&CK workbench

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-website#328]
Hi ,

I got an error when updating data from ATT&CK workbench. I add some new items base on Enterprise ATT&CK template in ATT&CK Workbench. i want to sync the data to attack-web so that i can show the data to my team easier. I updated the config according to this doc: https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/integrations.md

but when i run `python3 update-attack.py` it show an error as following:
![image](https://user-images.githubusercontent.com/8390209/130200226-578d8e9b-ea28-489a-8b20-ba5a20b81144.png)

is there any known issues about this?

**Comment by isaisabel** [comment]
This is not a known issue, this is the first time I've seen this. 

From the error it looks like there is at least one of your custom techniques doesn't have the `x_mitre_platforms` field (which stores platforms). It's possible that, if no platforms are defined, Workbench omits that property instead of setting it as an empty array for some reason.

I believe in the actual ATT&CK STIX data all techniques have defined platforms which is why we've never encountered this before.

As that field is required by in the STIX this is most likely a bug on the Workbench side of things since it's not producing data with the full set of fields required to be used in ATT&CK tools.

**Comment by isaisabel** [comment]
`attack-workbench-frontend` [initializes platforms as an empty array](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/develop/app/src/app/classes/stix/technique.ts#L13). So if you created a technique via the frontend I'm not sure how this would occur unless the REST API culls properties which are empty arrays for some reason (which seems unlikely). 

Have you created any of the input STIX data by hand, or edited them in the database directly? It's possible data that was not created via the normal means wouldn't be compliant with the full set of required fields.

**Comment by dickens88** [comment]
@isaisabel thank for your answer.
 I'm sure all the techniques I input to the workbench are typed from workbench frontend, i never call API or modify database directly.  I will try to fillup the  platforms fields and then feedback to you.

**Comment by isaisabel** [comment]
I'll see if I can reproduce the issue on my end as well.

**Comment by dickens88** [comment]
@isaisabel just as you analyzed, after i fillup the platforms field of teachnique, the `matrices` phase of update-attack.py can be run successfully. but then i got another error... i suppose it related to some other fileds missing as well ...

![image](https://user-images.githubusercontent.com/8390209/130240436-82adae60-7f3a-4456-8f54-0ff4445a3b63.png)

**Comment by isaisabel** [comment]
Have you defined any tactics for your techniques? This codebase is generally not very flexible for tactic-less techniques and vice versa (#73).

**Comment by dickens88** [comment]
Never, I used ATT&CK Enterprise pre-defined tactics  only.

**Comment by isaisabel** [comment]
I meant do you have any techniques without tactics defined? That's most likely the cause of the above error (it's looking for the tactic of a technique and can't find one).

**Comment by dickens88** [comment]
I don't think so, I made a testing server on cloud, currently i have only one customized technique (T2801) and it has related to a tactic. Maybe you can check my instance (if you have time). my testing server http://144.202.111.178/

**Comment by dickens88** [comment]
http://144.202.111.178:3000/api/stix-bundles/?domain=enterprise-attack

**Comment by isaisabel** [comment]
Yes there's something odd in your data there:
![image](https://user-images.githubusercontent.com/28868888/130243651-8b5c5655-088e-4b33-bb28-184eb4c4883e.png)

The phase name for your tactic is `command-and control` when it should be `command-and-control`. Let me see if I can dig up how that occured.

**Comment by dickens88** [comment]
well ... maybe it's bug. i just clicked the name on the web page. 

![image](https://user-images.githubusercontent.com/8390209/130243989-7470f68e-125f-4f2a-b0b6-c08e4c3fa79d.png)

**Comment by isaisabel** [comment]
Could be, it's had that name since the oldest version in your knowledge base (back when you had more tactics):
![image](https://user-images.githubusercontent.com/28868888/130244218-e590ff24-8283-4c5e-a227-6811bf93865c.png)

**Comment by isaisabel** [comment]
The tactic does have the correct phase_name in your database: 
![image](https://user-images.githubusercontent.com/28868888/130244435-c3496e90-7558-4bc2-8b5c-750f4bf9fdff.png)

**Comment by isaisabel** [comment]
Let me dig into the frontend codebase and see if I can find anything that might cause this.

**Comment by dickens88** [comment]
This knowledge base is downloaded from ATT&CK officla repos I think. yes please.

**Comment by isaisabel** [comment]
Found the bug, should have a fix out shortly.

https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/239

**Comment by dickens88** [comment]
super cool! thank you very much, I'm looking forward for the release.

**Comment by dickens88** [comment]
maybe you can check for antoher issue, if i leave the platform field empty, the update-attack.py will also get error. so maybe you can give it a suitable default value or made this platform as a required filed.

**Comment by isaisabel** [comment]
[v1.0.2 fixes the tactic shortnames bug](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/releases/tag/v1.0.2).

I've not yet been able to reproduce the platform issue, but I'll keep digging.

**Comment by dickens88** [comment]
Maybe you can try it on my test server. I changed the technique `T2801` and keep the platforms field as empty. then if you made http://144.202.111.178:3000/api/stix-bundles/?domain=enterprise-attack as your data source in attack-web and run `python3 update-attack.py` you will see the error.

**Comment by isaisabel** [comment]
OK so I did a bit more digging into the platforms issue, it appears that it's actually an ATT&CK Website bug. The data exported by Workbench is actually correct, it does include `x_mitre_platforms` as an empty array:

![Screen Shot 2021-08-20 at 1 37 38 PM](https://user-images.githubusercontent.com/28868888/130272804-91e17d4f-8299-469f-ab35-a6a535c85022.png)

If you take the stock ATT&CK STIX data and remove the platforms values from any technique (setting it to an empty array) the website will throw the same error. So the website must be doing some sort of culling of the `x_mitre_platforms` field on its end, which is odd behavior.

We'll dig into this more soon, but for now the solution is to ensure data consumed by attack-website always has a platform defined.

**Comment by isaisabel** [comment]
Superseded by #329.
