### ISSUE TITLE
Remove July 2020 Contribution update

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#331]
As a user, I do not want to be confused by outdated guidance and announcements.

The July 2020 Contribution update on the contribute page is quite out of date and should be removed altogether. 

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/28868888/131519235-5da2b90d-0c10-432c-b71b-b7d5e5528fc0.png">

**Comment by IanDavila** [comment]
Completed in `feature/#321-data-source-pages`. Will stage the rest of the milestone issues in that branch
