### ISSUE TITLE
Got error when trying to sync data from ATT&CK workbench

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-website#333]
Hi @isaisabel ,

I got a new issue when sync data from Workbench(v1.0.2) to attack-website(v3.3.1), it looks very similar with #328 but with different error message.

![image](https://user-images.githubusercontent.com/8390209/134324527-aa90af32-31ce-489d-8ea2-47432aa3a0b0.png)

it looks like the field `ctiaction` is missing, but i didn't find it at the web page. is there any known issue about this?

**Comment by isaisabel** [comment]
This should have been fixed in version 3.4.0.
