### ISSUE TITLE
Groups redirect is not built

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#338]
As a maintainer of attack-website, I want the [groups redirect](https://github.com/mitre-attack/attack-website/blob/gh-pages/groups.html) to be built to redirect users linking `attack.mitre.org/groups.html` to the new groups list page. Currently, that page is not being built by the site and has to manually generated as part of the publish process.

**Comment by jondricek** [comment]
this has now been addressed in the 3.6.0 release last week
