### ISSUE TITLE
Got error when pulling data from Workbench

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-website#342]
Hi ,

I'm using attack-website latest version 3.4.3, and I got an error when run `python3 update-attack.py`. the errow shown below. 

![image](https://user-images.githubusercontent.com/8390209/146746283-d0976862-6a8c-48ad-a171-9e580d7fe7e8.png)

I integrated website with attack-workbench accroding to [this guide](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docs/integrations.md). 
At beginning it works fine, but after i add some new records visa workbench and come back to update website with `python3 update-attack.py` the error happened.

It seems that some fields are missing, but i didn't see any notice related to that when i edit record in workbench.

**Comment by IanDavila** [comment]
Hi @dickens88, looks like one of the techniques in your workbench instance is missing a Tactic. Can you let me know if that is the case?

**Comment by dickens88** [comment]
@IanDavila you are right, i missed tactic in a new technique, it didn't seem to be mandatory, so I left it out... maybe workbench should make it mandatory so that no one will miss it. thanks.

**Comment by IanDavila** [comment]
Good idea @dickens88, will open an issue in the Workbench repository. Thank you!
