### ISSUE TITLE
Changelog inconsistencies

### ISSUE THREAD

**Issue by IanDavila** [mitre-attack/attack-website#351]
As a user, I want to be able to track accurately the dates on the changelog page. Currently, the latest date is pointing to January 2021 but it should be January 2022. 

Another issue with the changelog page is that the content shifts to the right when viewing from a large monitor or when decreasing the zoom.

**Comment by jondricek** [comment]
The first part of this has been addressed. I'll create a new issue for the content shifting to the right on large monitors
