### ISSUE TITLE
Properly include { and } inside of <code></code>

### ISSUE THREAD

**Issue by IanDavila** [mitre-attack/attack-website#353]
As a developer of the ATT&CK content, I want to be able to properly add {, } inside of \<code\> snippets. Currently a { gets translated to a {{, same behavior for }. `clean_stix_data` in `custom_jinja_filters.py` is making that replacement and needs to be updated to accommodate this need.

**Comment by jondricek** [comment]
Sort of a note to self - these are the references to where that code is used that I'll want to go over to make sure that the fix in the pull request looks right.

https://github.com/mitre-attack/attack-website/search?q=stixToHTML

**Comment by jondricek** [comment]
This was addressed in 3b23cfa7a062045063bd2a7b1ea71f890f3ced03, along with several other fixes.

**Comment by jondricek** [comment]
This was addressed in 3b23cfa7a062045063bd2a7b1ea71f890f3ced03, along with several other fixes.
