### ISSUE TITLE
Workbench non-deprecated mitigation relationships with techniques are being removed

### ISSUE THREAD

**Issue by IanDavila** [mitre-attack/attack-website#358]
When integrating the data from workbench, mitigation relationships with techniques must be handled appropriately. Currently, Workbench is correctly tagging the new relationships as `'x-mitre-deprecated': false` but the website build is incorrectly handling them as deprecated. The website build must be fixed to not remove those non-deprecated relationships by mistake.

**Comment by jondricek** [comment]
This was addressed in 3b23cfa7a062045063bd2a7b1ea71f890f3ced03, along with several other fixes.
