### ISSUE TITLE
Got an error when update data

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-website#370]
Hi ,

I updated the latest master branch v3.6.0. I changed the `site_config.py` to let the website sync data from my customized data source (ATT&CK Workbench). It got an error when I trying to run `python3 update_attack.py` which was shown like this,

![image](https://user-images.githubusercontent.com/8390209/166667855-6171ad13-14ef-4fb2-961f-326136fb1cee.png)

I suppose maybe some of the objects in the ATT&CK database missed stix id or something. anyway, with the same dataset, the previous release was fine. Is there anyway to skip this checking? or maybe need to change code to ignore this error. thanks.

**Comment by jondricek** [comment]
In the 3.6.1 release of the website last week, I moved the new `stixtests` module to be an optional test to run instead f by default, so this should be addressed now. Feel free to re-open the issue if it doesn't go away
