### ISSUE TITLE
Techniques table is empty for the Mobile Tactics Network Effects and Remote Service Effects

### ISSUE THREAD

**Issue by watgh** [mitre-attack/attack-website#392]
In version 10, Network Effects and Remote Service Effects had Techniques in the Mobile Matrix.  As of Version 11, these techniques were apparently moved.  The Techniques table is now empty.  The question is, should these tactics have been deprecated?  Are there still valid tactics.  I'm submitting this to both mitre/cti (#205) and mitre-attack/attack-website (#392)..  -- Thanks!

**Comment by jondricek** [comment]
Thanks for the feedback! In this case it was an oversight on our end and we will be deprecating both of the following Tactics in the 12.1 release tomorrow since, as you've pointed out, we have no current active Techniques mapped to them.

* TA0038: Network Effects
* TA0039: Remote Service Effects
