### ISSUE TITLE
Search functionality improvement

### ISSUE THREAD

**Issue by burritoblue** [mitre-attack/attack-website#4]
As a user, I'd like to have better feedback when using the search bar in the ATT&CK website. Some suggested improvements:
1. Bigger search bar and list of results
2. Possibility to filter results: only techniques, only enterprise, only windows, hide deprecated, etc.
3. Visual highlight of the different types of results: enterprise vs mobile, technique vs tactic

**Comment by isaisabel** [comment]
Hi @burritoblue,

Sorry for the long turn around. We've been working on some search improvements which can be found on the `feature/#4-search` branch. The search interface should have a much better user experience than the previous implementation.

**Comment by isaisabel** [comment]
@IanDavila, when you have time could you do compatibility testing of this feature for IE/Edge? I've already tested chrome, firefox and safari. Thanks!

**Comment by isaisabel** [comment]
This feature has been implemented and merged into develop. See PR #74.
