### ISSUE TITLE
Print style sheet for Techniques

### ISSUE THREAD

**Issue by jondricek** [mitre-attack/attack-website#403]
Right now it is really tricky to print a Technique or save as PDF from https://attack.mitre.org. An example below shows what the print preview looks like for T1548.001 [Abuse Elevation Control Mechanism: Setuid and Setgid](https://attack.mitre.org/techniques/T1548/001/)

It would be very useful to have an alternate CSS stylesheet for printing that would help display the information in a more appropriate display.

![image](https://user-images.githubusercontent.com/90368810/226457428-7d97f8f0-8ca2-4335-8372-c8b1304dd9e7.png)

**Comment by vsun757** [comment]
Fix merged into attack website. Closing now.
