### ISSUE TITLE
font-awesome and air-gaps

### ISSUE THREAD

**Issue by ForsetiJan** [mitre-attack/attack-website#488]
We run a copy of the website on an air-gapped environment for easier reference for our analysts. Since the update to v14 we have experienced issues loading any page until explicitly cancelled. This is caused by client attempting to load `font-awesome.min.css` from `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/<version</css/font-awesome.min.css`

I would like to suggest to include the font in the application to allow for offline hosting. The [MIT license](https://fontawesome.com/v4/license/) should allow for it.

**Comment by jondricek** [comment]
We just addressed this in the latest version of the website today (version 4.1.0). Let us know if you have any issues with it!

**Comment by ForsetiJan** [comment]
The specific issue was fixed however I believe there is one more we should move locally. It doesn't affect performance or usability but the app is trying to access:

`https://cdnjs.cloudflare.com/ajax/libs/uswds/3.7.1/fonts/source-sans-pro/sourcesanspro-regular-webfront.woff22` 
to which it was referred by 
`https://cdnjs.cloudflare.com/ajax/libs/uswds/3.7.1/css/uswds.min.css`

This points me this to this line:
https://github.com/mitre-attack/attack-website/blob/fa7f502b74bf93886101449e72411c281179fae2/attack-theme/templates/general/base-template.html#L46

**Comment by clemiller** [comment]
Hi @ForsetiJan, just a quick update to let you know that we have removed the USWDS CDN link from the `base-template`.
