### ISSUE TITLE
Cloning the project on Windows platforms

### ISSUE THREAD

**Issue by RalucaPreda** [mitre-attack/attack-website#5]
The project cannot be cloned on Windows platforms, due to the ":" placed in the names of some folders (example path: plugins/caltack/static/attack-website/mobile/index.php/Manual:Copyright)

**Comment by isaisabel** [comment]
Hi @RalucaPreda,

We have removed the offending files in a recent update, however If you checkout previous commits you may still have an issue since we did not delete them from git history.
