### ISSUE TITLE
Minor Type for Command and Scripting Interpreter: Cloud API page

### ISSUE THREAD

**Issue by PollJunkie** [mitre-attack/attack-website#518]
https://attack.mitre.org/techniques/T1059/009/ makes reference to "GCP Admin Acitivty " when it should say "GCP Admin Activity "

**Comment by jondricek** [comment]
Thanks for the help - we'll get this taken care of for the next release!

**Comment by jondricek** [comment]
Oh, and even though it isn't updated on the website yet I'm going to keep this issue closed as I'm now tracking this on our internal system. Just thought I should mention that too.

**Comment by PollJunkie** [comment]
Great, happy to help!
