### ISSUE TITLE
change log

### ISSUE THREAD

**Issue by SkyishOne** [mitre-attack/attack-website#522]
Hello,
Your medium.com article on what's new in ATT&CK 16 links to a change log here:
https://attack.mitre.org/changes/
![changelog404](https://github.com/user-attachments/assets/6a2f5045-efa2-4782-9f4c-8f7c70a5178b)
this page shows a 404 not found error.

**Comment by jondricek** [comment]
sorry about that! our blog post for the v16 release today initially had the incorrect link you are sharing there. the link has been fixed there, and should have pointed to this instead: https://attack.mitre.org/resources/updates/updates-october-2024/
