### ISSUE TITLE
WEBC2 is not one specific malware implant

### ISSUE THREAD

**Issue by wesinator** [mitre-attack/attack-website#7]
https://attack.mitre.org/software/S0109/ 
`WEBC2` is just a generic term for APT1 implants that use HTTP/HTML based C&C mechanisms.

Suggested change:
`WEBC2 is a backdoor used by APT1` -> `WEBC2 is malware used by APT1`

**Comment by isaisabel** [comment]
Hi @wesinator,

Feedback on the site content should be submitted via email to attack@mitre.org instead of tickets on this issue tracker. Please re-submit your feedback over email so the greater ATT&CK team can address it appropriately.
