### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by mark1973ryan** [mitre-attack/attack-website#95]
Hi,

Everything seems to be running fine. I'm on an open EC2 instance just for building but yet the process sticks on Initializing Data. Been around an hour so far.

Step 13/15 : RUN python3 update-attack.py -c -b
 ---> Running in 116617a74442
Clean Build            : ---------------------------------------- 0.00s
Downloading STIX Data  : ---------------------------------------- 1.39s
Initializing Data      : ---------------------------------------- Running...

Thanks

**Comment by isaisabel** [comment]
Hi @mark1973ryan,

We were unable to reproduce this issue locally, although we don't have an EC2 instance to test on. Typically the initializing data step takes about 1 minute. 

To assist in debugging, please provide us with the following information:
- What branch are you on?
- Did you modify any files before building (especially any files in `data/stix`)?
- Are you able to build the application without using docker (using the instructions in the README)?

**Comment by mark1973ryan** [comment]
I believe the issue was due to the server not having enough grunt. The build completed on a virtual box VM.
